package prueba;
// Generated 15/11/2013 12:12:37 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Dia generated by hbm2java
 */
public class Dia  implements java.io.Serializable {


     private int idDia;
     private String nombreDia;
     private String nomDia;
     private Set<GrupoDia> grupoDias = new HashSet<GrupoDia>(0);

    public Dia() {
    }

	
    public Dia(int idDia) {
        this.idDia = idDia;
    }
    public Dia(int idDia, String nombreDia, String nomDia, Set<GrupoDia> grupoDias) {
       this.idDia = idDia;
       this.nombreDia = nombreDia;
       this.nomDia = nomDia;
       this.grupoDias = grupoDias;
    }
   
    public int getIdDia() {
        return this.idDia;
    }
    
    public void setIdDia(int idDia) {
        this.idDia = idDia;
    }
    public String getNombreDia() {
        return this.nombreDia;
    }
    
    public void setNombreDia(String nombreDia) {
        this.nombreDia = nombreDia;
    }
    public String getNomDia() {
        return this.nomDia;
    }
    
    public void setNomDia(String nomDia) {
        this.nomDia = nomDia;
    }
    public Set<GrupoDia> getGrupoDias() {
        return this.grupoDias;
    }
    
    public void setGrupoDias(Set<GrupoDia> grupoDias) {
        this.grupoDias = grupoDias;
    }




}


