package prueba;
// Generated 15/11/2013 12:12:37 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private int idGrupo;
     private Profesor profesor;
     private Turno turno;
     private CurriculaAnual curriculaAnual;
     private Date fecInicio;
     private Date fecTermino;
     private String numMatriculados;
     private Integer cantMaximaAlumno;
     private Set<GrupoDia> grupoDias = new HashSet<GrupoDia>(0);
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);

    public Grupo() {
    }

	
    public Grupo(int idGrupo, Profesor profesor, Turno turno, CurriculaAnual curriculaAnual) {
        this.idGrupo = idGrupo;
        this.profesor = profesor;
        this.turno = turno;
        this.curriculaAnual = curriculaAnual;
    }
    public Grupo(int idGrupo, Profesor profesor, Turno turno, CurriculaAnual curriculaAnual, Date fecInicio, Date fecTermino, String numMatriculados, Integer cantMaximaAlumno, Set<GrupoDia> grupoDias, Set<Matricula> matriculas) {
       this.idGrupo = idGrupo;
       this.profesor = profesor;
       this.turno = turno;
       this.curriculaAnual = curriculaAnual;
       this.fecInicio = fecInicio;
       this.fecTermino = fecTermino;
       this.numMatriculados = numMatriculados;
       this.cantMaximaAlumno = cantMaximaAlumno;
       this.grupoDias = grupoDias;
       this.matriculas = matriculas;
    }
   
    public int getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(int idGrupo) {
        this.idGrupo = idGrupo;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public CurriculaAnual getCurriculaAnual() {
        return this.curriculaAnual;
    }
    
    public void setCurriculaAnual(CurriculaAnual curriculaAnual) {
        this.curriculaAnual = curriculaAnual;
    }
    public Date getFecInicio() {
        return this.fecInicio;
    }
    
    public void setFecInicio(Date fecInicio) {
        this.fecInicio = fecInicio;
    }
    public Date getFecTermino() {
        return this.fecTermino;
    }
    
    public void setFecTermino(Date fecTermino) {
        this.fecTermino = fecTermino;
    }
    public String getNumMatriculados() {
        return this.numMatriculados;
    }
    
    public void setNumMatriculados(String numMatriculados) {
        this.numMatriculados = numMatriculados;
    }
    public Integer getCantMaximaAlumno() {
        return this.cantMaximaAlumno;
    }
    
    public void setCantMaximaAlumno(Integer cantMaximaAlumno) {
        this.cantMaximaAlumno = cantMaximaAlumno;
    }
    public Set<GrupoDia> getGrupoDias() {
        return this.grupoDias;
    }
    
    public void setGrupoDias(Set<GrupoDia> grupoDias) {
        this.grupoDias = grupoDias;
    }
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }




}


