package prueba;
// Generated 15/11/2013 12:12:37 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Especialidad generated by hbm2java
 */
public class Especialidad  implements java.io.Serializable {


     private int idEspecialidad;
     private ResolucionDirectoral resolucionDirectoral;
     private String nombreEspecialidad;
     private String cicloEspecialidad;
     private Set<Modulo> modulos = new HashSet<Modulo>(0);
     private Set<CurriculaAnual> curriculaAnuals = new HashSet<CurriculaAnual>(0);

    public Especialidad() {
    }

	
    public Especialidad(int idEspecialidad, ResolucionDirectoral resolucionDirectoral) {
        this.idEspecialidad = idEspecialidad;
        this.resolucionDirectoral = resolucionDirectoral;
    }
    public Especialidad(int idEspecialidad, ResolucionDirectoral resolucionDirectoral, String nombreEspecialidad, String cicloEspecialidad, Set<Modulo> modulos, Set<CurriculaAnual> curriculaAnuals) {
       this.idEspecialidad = idEspecialidad;
       this.resolucionDirectoral = resolucionDirectoral;
       this.nombreEspecialidad = nombreEspecialidad;
       this.cicloEspecialidad = cicloEspecialidad;
       this.modulos = modulos;
       this.curriculaAnuals = curriculaAnuals;
    }
   
    public int getIdEspecialidad() {
        return this.idEspecialidad;
    }
    
    public void setIdEspecialidad(int idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }
    public ResolucionDirectoral getResolucionDirectoral() {
        return this.resolucionDirectoral;
    }
    
    public void setResolucionDirectoral(ResolucionDirectoral resolucionDirectoral) {
        this.resolucionDirectoral = resolucionDirectoral;
    }
    public String getNombreEspecialidad() {
        return this.nombreEspecialidad;
    }
    
    public void setNombreEspecialidad(String nombreEspecialidad) {
        this.nombreEspecialidad = nombreEspecialidad;
    }
    public String getCicloEspecialidad() {
        return this.cicloEspecialidad;
    }
    
    public void setCicloEspecialidad(String cicloEspecialidad) {
        this.cicloEspecialidad = cicloEspecialidad;
    }
    public Set<Modulo> getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Set<Modulo> modulos) {
        this.modulos = modulos;
    }
    public Set<CurriculaAnual> getCurriculaAnuals() {
        return this.curriculaAnuals;
    }
    
    public void setCurriculaAnuals(Set<CurriculaAnual> curriculaAnuals) {
        this.curriculaAnuals = curriculaAnuals;
    }




}


