package prueba;
// Generated 15/11/2013 12:12:37 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProgCurricular generated by hbm2java
 */
public class ProgCurricular  implements java.io.Serializable {


     private int idProgCurricular;
     private Date fecRegistro;
     private String detalle;
     private Set<CurriculaAnual> curriculaAnuals = new HashSet<CurriculaAnual>(0);

    public ProgCurricular() {
    }

	
    public ProgCurricular(int idProgCurricular) {
        this.idProgCurricular = idProgCurricular;
    }
    public ProgCurricular(int idProgCurricular, Date fecRegistro, String detalle, Set<CurriculaAnual> curriculaAnuals) {
       this.idProgCurricular = idProgCurricular;
       this.fecRegistro = fecRegistro;
       this.detalle = detalle;
       this.curriculaAnuals = curriculaAnuals;
    }
   
    public int getIdProgCurricular() {
        return this.idProgCurricular;
    }
    
    public void setIdProgCurricular(int idProgCurricular) {
        this.idProgCurricular = idProgCurricular;
    }
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Set<CurriculaAnual> getCurriculaAnuals() {
        return this.curriculaAnuals;
    }
    
    public void setCurriculaAnuals(Set<CurriculaAnual> curriculaAnuals) {
        this.curriculaAnuals = curriculaAnuals;
    }




}


