package modelo;
// Generated 15/11/2013 12:12:37 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CurriculaAnual generated by hbm2java
 */
public class CurriculaAnual  implements java.io.Serializable {


     private String idCurriculaAnual;
     private Especialidad especialidad;
     private ProgCurricular progCurricular;
     private Set<Grupo> grupos = new HashSet<Grupo>(0);

    public CurriculaAnual() {
    }

	
    public CurriculaAnual(String idCurriculaAnual, Especialidad especialidad, ProgCurricular progCurricular) {
        this.idCurriculaAnual = idCurriculaAnual;
        this.especialidad = especialidad;
        this.progCurricular = progCurricular;
    }
    public CurriculaAnual(String idCurriculaAnual, Especialidad especialidad, ProgCurricular progCurricular, Set<Grupo> grupos) {
       this.idCurriculaAnual = idCurriculaAnual;
       this.especialidad = especialidad;
       this.progCurricular = progCurricular;
       this.grupos = grupos;
    }
   
    public String getIdCurriculaAnual() {
        return this.idCurriculaAnual;
    }
    
    public void setIdCurriculaAnual(String idCurriculaAnual) {
        this.idCurriculaAnual = idCurriculaAnual;
    }
    public Especialidad getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(Especialidad especialidad) {
        this.especialidad = especialidad;
    }
    public ProgCurricular getProgCurricular() {
        return this.progCurricular;
    }
    
    public void setProgCurricular(ProgCurricular progCurricular) {
        this.progCurricular = progCurricular;
    }
    public Set<Grupo> getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set<Grupo> grupos) {
        this.grupos = grupos;
    }




}


