package modelo;
// Generated 15/11/2013 12:12:37 AM by Hibernate Tools 3.2.1.GA



/**
 * GrupoDia generated by hbm2java
 */
public class GrupoDia  implements java.io.Serializable {


     private GrupoDiaId id;
     private Grupo grupo;
     private Dia dia;
     private String descripcionGrupoDia;

    public GrupoDia() {
    }

	
    public GrupoDia(GrupoDiaId id, Grupo grupo, Dia dia) {
        this.id = id;
        this.grupo = grupo;
        this.dia = dia;
    }
    public GrupoDia(GrupoDiaId id, Grupo grupo, Dia dia, String descripcionGrupoDia) {
       this.id = id;
       this.grupo = grupo;
       this.dia = dia;
       this.descripcionGrupoDia = descripcionGrupoDia;
    }
   
    public GrupoDiaId getId() {
        return this.id;
    }
    
    public void setId(GrupoDiaId id) {
        this.id = id;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Dia getDia() {
        return this.dia;
    }
    
    public void setDia(Dia dia) {
        this.dia = dia;
    }
    public String getDescripcionGrupoDia() {
        return this.descripcionGrupoDia;
    }
    
    public void setDescripcionGrupoDia(String descripcionGrupoDia) {
        this.descripcionGrupoDia = descripcionGrupoDia;
    }




}


