package modelo;
// Generated 15/11/2013 12:12:37 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private MatriculaId id;
     private Grupo grupo;
     private Alumno alumno;
     private Date fecMatricula;
     private String observacion;

    public Matricula() {
    }

	
    public Matricula(MatriculaId id, Grupo grupo, Alumno alumno) {
        this.id = id;
        this.grupo = grupo;
        this.alumno = alumno;
    }
    public Matricula(MatriculaId id, Grupo grupo, Alumno alumno, Date fecMatricula, String observacion) {
       this.id = id;
       this.grupo = grupo;
       this.alumno = alumno;
       this.fecMatricula = fecMatricula;
       this.observacion = observacion;
    }
   
    public MatriculaId getId() {
        return this.id;
    }
    
    public void setId(MatriculaId id) {
        this.id = id;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Date getFecMatricula() {
        return this.fecMatricula;
    }
    
    public void setFecMatricula(Date fecMatricula) {
        this.fecMatricula = fecMatricula;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


