package modelo;
// Generated 15/11/2013 12:12:37 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int idAlumno;
     private String nombres;
     private String apePaterno;
     private String apeMaterno;
     private Date fecNacimiento;
     private Character sexo;
     private Integer dni;
     private String email;
     private Integer edad;
     private Integer numFijo;
     private Integer numMovil;
     private String domicilio;
     private String provincia;
     private String region;
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);

    public Alumno() {
      
    }

	
   
    public Alumno(int idAlumno, String nombres, String apePaterno, String apeMaterno, Date fecNacimiento, Character sexo, Integer dni, String email, Integer edad, Integer numFijo, Integer numMovil, String domicilio, String provincia, String region, Set<Matricula> matriculas) {
       this.idAlumno = idAlumno;
       this.nombres = nombres;
       this.apePaterno = apePaterno;
       this.apeMaterno = apeMaterno;
       this.fecNacimiento = fecNacimiento;
       this.sexo = sexo;
       this.dni = dni;
       this.email = email;
       this.edad = edad;
       this.numFijo = numFijo;
       this.numMovil = numMovil;
       this.domicilio = domicilio;
       this.provincia = provincia;
       this.region = region;
       this.matriculas = matriculas;
    }
   
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApePaterno() {
        return this.apePaterno;
    }
    
    public void setApePaterno(String apePaterno) {
        this.apePaterno = apePaterno;
    }
    public String getApeMaterno() {
        return this.apeMaterno;
    }
    
    public void setApeMaterno(String apeMaterno) {
        this.apeMaterno = apeMaterno;
    }
    public Date getFecNacimiento() {
        return this.fecNacimiento;
    }
    
    public void setFecNacimiento(Date fecNacimiento) {
        this.fecNacimiento = fecNacimiento;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Integer getNumFijo() {
        return this.numFijo;
    }
    
    public void setNumFijo(Integer numFijo) {
        this.numFijo = numFijo;
    }
    public Integer getNumMovil() {
        return this.numMovil;
    }
    
    public void setNumMovil(Integer numMovil) {
        this.numMovil = numMovil;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }




}


