package modelo;
// Generated 15/11/2013 12:12:37 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ResolucionDirectoral generated by hbm2java
 */
public class ResolucionDirectoral  implements java.io.Serializable {


     private int idRd;
     private Integer anioInicio;
     private Integer anioTermino;
     private Date fecRegistro;
     private Set<Especialidad> especialidads = new HashSet<Especialidad>(0);

    public ResolucionDirectoral() {
    }

	
    public ResolucionDirectoral(int idRd) {
        this.idRd = idRd;
    }
    public ResolucionDirectoral(int idRd, Integer anioInicio, Integer anioTermino, Date fecRegistro, Set<Especialidad> especialidads) {
       this.idRd = idRd;
       this.anioInicio = anioInicio;
       this.anioTermino = anioTermino;
       this.fecRegistro = fecRegistro;
       this.especialidads = especialidads;
    }
   
    public int getIdRd() {
        return this.idRd;
    }
    
    public void setIdRd(int idRd) {
        this.idRd = idRd;
    }
    public Integer getAnioInicio() {
        return this.anioInicio;
    }
    
    public void setAnioInicio(Integer anioInicio) {
        this.anioInicio = anioInicio;
    }
    public Integer getAnioTermino() {
        return this.anioTermino;
    }
    
    public void setAnioTermino(Integer anioTermino) {
        this.anioTermino = anioTermino;
    }
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }
    public Set<Especialidad> getEspecialidads() {
        return this.especialidads;
    }
    
    public void setEspecialidads(Set<Especialidad> especialidads) {
        this.especialidads = especialidads;
    }




}


